config/routes.rb
RailsTemplate::Application.routes.draw do

  match '/auth/:provider/callback', to: 'authentications#create', via: 'get'

  resources :authentications
  resources :password_resets
  resources :profiles 

  resources :users, except: [:show] do
    resources :verify_emails, only: [:new, :create]
    resources :reset_verify_emails, only: [:new, :create]
#    resources :change_usernames, only: [:edit, :update], shallow: true
#    resources :change_emails, only: [:edit, :update], shallow: true
#    resources :change_avatars, only: [:edit, :update], shallow: true
  end

  get '/users/:id', to: "profiles#show"

#  resources :change_usernames, only: [:edit, :update]

  get 'user_location/edit', to: "user_locations#edit", as: :edit_user_location
  post 'user_location', to: "user_locations#update", as: :user_location
 
  get 'user_avatar/edit', to: "change_avatars#edit", as: :edit_user_avatar
  match 'user_avatar', to: "change_avatars#update", as: :user_avatar, via: ['put', 'patch']

  get 'username/edit', to: "change_usernames#edit", as: :edit_username
  match 'username', to: "change_usernames#update", as: :username, via: ['put', 'patch']

  get 'user_email/edit', to: "change_emails#edit", as: :edit_user_email
  match 'user_email', to: "change_emails#update", as: :user_email, via: ['put', 'patch']

  post '/profiles/:id/enable_personal_on', to: "profiles#enable_personal_on",
  as: :enable_personal_profile_on
  resource :personal_profile, except: [:new, :create] do
    member do
      get 'edit_wants'
    end
  end

  get '/users/:user_id/verify_email_token/:verify_token', 
       to: "verify_emails#create", as: 'verify_email_token'
 
  resources :sessions, only: [:new, :create, :destroy]

  root  'static_pages#home'
  match '/signup',  to: 'users#new', via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'

  match '/home', to: 'static_pages#home', via: 'get'
  match '/help', to: 'static_pages#help', via: 'get'
  match '/about', to: 'static_pages#about', via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/error', to: 'static_pages#error', via: 'get'

  match '~:id' => 'profiles#show', :as => :show_profile, via: 'get', :constraints => { :username => /[A-Za-z0-9_\.]+/ }

end

app/models/user.rb
class User < ActiveRecord::Base
  belongs_to :geo_country
  belongs_to :geo_area
  has_one :profile
  has_many :events
  has_many :authentications

  before_create :create_remember_token
  before_create :init_new_user
  before_create :init_profile

	before_save { email.downcase! }
  before_save { username.try(:downcase!) }

  before_save :update_age

  mount_uploader :avatar, AvatarUploader
  
  attr_accessor :verify_token, :unhashed_email_validation_token, 
                :zip_code, :auth_type

  VALIDATION_CODE_RESET_MESSAGE = "Your email validation code has been reset and emailed to you."

  PASSWORD_RESET_TTL_HOURS = CONFIG[:password_reset_ttl_hours] || 2

  NAME_MAX_LENGTH = 32
  NAME_MIN_LENGTH = 2
  USERNAME_MAX_LENGTH = 24
  USERNAME_MIN_LENGTH = 2
  EMAIL_MAX_LENGTH = 50
  EMAIL_MIN_LENGTH = 4
	
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(?:\.[a-z\d\-]+)*\.[a-z]+\z/i
  VALID_NAME_REGEX = /\A[a-z\d\-\_\.\&\s]+\z/i
  VALID_USERNAME_REGEX = /\A[a-z]{1}[a-z\d\-\_]+\z/i

  AUTH_TYPES = ["local", "omniauth"]
  AUTH_LOCAL = AUTH_TYPES[0]
  AUTH_OMNIAUTH = AUTH_TYPES[1]
  
  AGE_DISPLAY_TYPES = ["Hidden", "Number", "Range"]

  AGE_DISPLAY_HIDDEN = AGE_DISPLAY_TYPES[0]
  AGE_DISPLAY_NUMBER = AGE_DISPLAY_TYPES[1]
  AGE_DISPLAY_RANGE = AGE_DISPLAY_TYPES[2]

  AGE_RANGE_MAP = [ 
    { min: 0, max: 17, text: "Under 18 years old"},
    { min: 18, max: 25, text: "18-25 years old"},
    { min: 26, max: 35, text: "26-35 years old"},
    { min: 36, max: 45, text: "36-45 years old"},
    { min: 46, max: 55, text: "36-55 years old"},
    { min: 56, max: 65, text: "56-65 years old"},
    { min: 66, max: 75, text: "66-75 years old"},
    { min: 76, max: 200, text: "76 years or older"}    
  ]


  VALID_GENDERS = ["Male", "Female", "Transgender", "Other"]
  MALE_VALUE = VALID_GENDERS[0]
  FEMALE_VALUE = VALID_GENDERS[1]
  TRANSGENDER_VALUE = VALID_GENDERS[2]
  OTHER_GENDER_VALUE = VALID_GENDERS[3] 

  VALID_AVATAR_TYPES = ["None", "Gravatar", "Upload"]
  NO_AVATAR = VALID_AVATAR_TYPES[0]
  GRAVATAR_AVATAR = VALID_AVATAR_TYPES[1]
  UPLOAD_AVATAR = VALID_AVATAR_TYPES[2]

  GRAVATAR_SIZE_MAP = { tiny: "50", small: "70", medium: "100", large: "150"}
  GRAVITAR_DEFAULT_SIZE = GRAVATAR_SIZE_MAP[:small]
  IMAGE_RESIZE_MAP = { tiny: [30, 30], small:[60, 60] , medium: [100, 100], 
                     large: [200, 200], original: [400, 400] }

   
  DEFAULT_AVATAR_DIR = CONFIG[:default_avatar_dir] || "/images/default_avatar"

  START_YEAR = 1900
  VALID_DATES = DateTime.new(START_YEAR)..DateTime.now
  CURRENT_YEAR = DateTime.now.year

  MIN_AGE = CONFIG[:min_age].blank? ? nil : CONFIG[:min_age].to_i
  MAX_AGE = CONFIG[:max_age].blank? ? nil : CONFIG[:max_age].to_i 
  HAS_USER_EDIT_FIELDS = (CONFIG[:enable_name?] || CONFIG[:enable_gender?] || 
                          CONFIG[:enable_birthdate?] || CONFIG[:enable_time_zone?] )

  name_can_be_blank = CONFIG[:require_name?] ? false : true
  username_can_be_blank = CONFIG[:require_username?] ? false : true
  gender_can_be_blank = CONFIG[:require_gender?] ? false : true
  birthdate_can_be_blank = CONFIG[:require_birthdate?] ? false : true
  time_zone_can_be_blank = CONFIG[:require_time_zone?] ? false : true
  country_can_be_blank = CONFIG[:require_country?] ? false : true
  zip_code_can_be_blank = CONFIG[:require_zip_code?] ? false : true

  #For each of the user_form_options define require_#{option_name} and
  #enable_#{option_name} methods and make each one a helper method as well
  CONFIG[:user_form_options].each do |option_name|
    enable_name = "enable_#{option_name}".to_sym
    require_name = "require_#{option_name}".to_sym
    use_name = "use_#{option_name}".to_sym
    define_method enable_name do
      CONFIG[enable_name]
    end
#    helper_method enable_name
    define_method require_name do
      CONFIG[require_name]
    end
#    helper_method require_name
    define_method use_name do 
      new_record? ? CONFIG[require_name] : CONFIG[enable_name]
    end
  end

  has_secure_password validations: false

  validates :password, presence: true, allow_blank: false, 
  confirmation: true, length: { minimum: 6 }, on: :create, 
  if: lambda { |u| u.password_required? }

  validates :name, allow_blank: name_can_be_blank, presence: !name_can_be_blank, 
            format: { with: VALID_NAME_REGEX },
            length: {minimum: NAME_MIN_LENGTH, maximum: NAME_MAX_LENGTH},
            if: "CONFIG[:enable_name?]"

  validates :geo_country, allow_blank: country_can_be_blank, presence: !country_can_be_blank,
            if: "CONFIG[:enable_country?]"
  validates :zip_code, allow_blank: zip_code_can_be_blank, presence: !zip_code_can_be_blank, 
            on: :create, if: "CONFIG[:enable_zip_code?]"
  validates :username, allow_blank: username_can_be_blank, presence: !username_can_be_blank, 
            format: { with: VALID_USERNAME_REGEX },
            uniqueness: { case_sensitive: false},
            length: {minimum: USERNAME_MIN_LENGTH, maximum: USERNAME_MAX_LENGTH},
            if: "CONFIG[:enable_username?]"
 
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }

  validates :gender, allow_blank: gender_can_be_blank, presence: !gender_can_be_blank, 
             inclusion: { in: VALID_GENDERS },
            if: "CONFIG[:enable_gender?]"
  validates :time_zone, allow_blank: time_zone_can_be_blank, presence: !time_zone_can_be_blank, 
             inclusion: { in: ActiveSupport::TimeZone.zones_map(&:name).keys },
            if: "CONFIG[:enable_time_zone?]"

  if CONFIG[:enable_birthdate?]
#    p "IN enable_birthdate validation. MIN_AGE = #{MIN_AGE}. birthdate_can_be_blank = #{birthdate_can_be_blank}"
    date_hash = { allow_blank: birthdate_can_be_blank }
    if !MIN_AGE.nil?
      date_hash.merge!(before: Proc.new { MIN_AGE.years.ago }, before_message: "must be at least #{MIN_AGE} years old")
    end
    if !MAX_AGE.nil?
      date_hash.merge!(on_or_after: Proc.new{ MAX_AGE.years.ago }, on_or_after_message: "Cannot be more than #{MAX_AGE} years old")
    end
    validates_date :birthdate,  date_hash
  end

  if CONFIG[:user_identity_field] == 'username'
    def to_param
      self.username
    end

    def self.find(identifier)
      self.find_by_username(identifier)
    end
  end

  def User.find_by_identity(ident, args={})
    field = CONFIG[:user_identity_field]
#    puts "args = #{args.inspect}"
#    puts "arg class = args.class.inspect"
    ret = where(field => ident)
    if args[:include]
      ret = ret.includes(args[:include])
    end
    ret.first
  end

  def User.username_taken?(uname)
    where(username: uname).take ? true : false
  end
  
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  def User.make_hash(token)
    Digest::SHA1.hexdigest(token.to_s)
  end
  
  def User.build_default_avatar_url(opts={})
    size = opts[:size] || nil
    gender = opts[:gender] || nil
    filename = size.nil? ? "avatar.png" : "#{size.to_s.downcase}_avatar.png"
    if gender.nil?
      "#{DEFAULT_AVATAR_DIR}/default/{filename}"
    else
      "#{DEFAULT_AVATAR_DIR}/#{gender.to_s.downcase}/#{filename}" 
    end
  end

  def User.display_age_range(age, map = AGE_RANGE_MAP)
    ret = ""
    logger.debug("map = #{map.inspect}")
    if (age)
      map.each do |map_item|
        logger.debug("map_item = #{map_item.inspect}")
        logger.debug("age = '#{age}', min = '#{map_item[:min]}', max = '#{map_item[:max]}'")
        if age >= map_item[:min] && age <= map_item[:max] 
          ret = map_item[:text]
          break
        end
      end
    else
      logger.warn("WARNING! Age not specified in display_age_range")
    end
    ret
  end

  def has_local_authentication?
    !password_digest.blank?
  end

  def num_authentications
    authentications.length
  end

  def password_required?
    (authentications.empty? || !password.blank?)
  end

  def display_age_range
    ret = ""
    if (age)
      ret = self.class.display_age_range(age)
    else
      if CONFIG[:require_birthdate?]
        logger.warn("WARNING! Age not specified for user.id #{self.id}")
      end
    end
    ret
  end

  def display_age
    ret = ""
    case self.age_display_type
    when AGE_DISPLAY_HIDDEN
      ret = "Private"
    when AGE_DISPLAY_NUMBER
      ret = self.age
    when AGE_DISPLAY_RANGE
      ret = display_age_range
    else
      raise "No valid display age: #{self.age_display_type} in display_age"
    end
    ret
  end

  def display_location
    self.geo_area.display
  end

 # def to_param
 #   self.username || self.id
 # end

  def zip_code
    @zip_code || geo_area.try(:zip)
  end

#  def self.find(identifier)
#    self.find_by_username(identifier)
#  end

  def init_unvalidated_email
    if CONFIG[:verify_email?]
      token = User.new_token
      logger.debug("Setting new email validation token to '#{token}'")
      self.unhashed_email_validation_token = token
      self.email_validation_token = User.make_hash(token)
      self.email_validated = false
    end
    self.email_changed_at = Time.zone.now
    self.email.downcase!
  end

  def reset_email(new_email)
    self.email = new_email
    init_unvalidated_email
    save!
  end

  def reset_email_validation_token(overide_token=nil)
    #helpful for testing
    token = overide_token.nil? ? User.new_token : overide_token
    self.unhashed_email_validation_token = token
    hashed_token = User.make_hash(token)
    self.email_validation_token = hashed_token
    self.email_validated = false
    { token: token, hashed_token: hashed_token}
  end

  def send_email_validation_token
    unless self.email_validation_token && self.unhashed_email_validation_token
      raise "email_validation_token is not set when attempting to email the validation code"
    end
    UserMailer.email_validation_token(self).deliver
  end

  def send_email_changed_validation_token
    unless self.email_validation_token && self.unhashed_email_validation_token

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :signed_in_user, only: [:index, :edit, :update, :destroy]
	before_action :correct_user,   only: [:edit, :update]
  before_action :admin_user,     only: :destroy
  before_action :is_signed_in,   only: [:new, :create]

  def index
  	@users = User.paginate(page: params[:page])
  end

	def show
    puts 'IN SHOW!!!'
    logger.debug("IN user show")
    @user = User.find(params[:id])
    logger.debug("Got user = #{@user.inspect}")
  end

  def new
  	@user = new_user
    logger.debug("user.name = #{@user.name}")
#    @countries = GeoCountry.get_country_list({default_country: CONFIG[:default_country],
#                                              force_reaload: true})
    load_new_user_info
  end

  def create
    @user = new_user(user_params)  
#    p "IN CREATE: @user.gender = '#{@user.gender}', @user.birthdate = '#{@user.birthdate}'"
    @user.set_create_ip_addresses(request.remote_ip)
    if @user.save
      profile = @user.build_profile
      profile.save
    	sign_in @user
      session[:omniauth] = nil
      if CONFIG[:verify_email?]
        @user.send_email_validation_token
        redirect_to new_user_verify_email_path(@user)
#        render 'show_verify_email'
      else
    	  flash[:success] = "Welcome. You have registered for the site!"
        redirect_to @user
      end
    else
      load_new_user_info
      render 'new'
    end
  end

  def edit
    @user = current_user
    load_new_user_info
  end

  def update
    @user = current_user
    if @user.update_attributes(user_params)
    	flash[:success] = "Profile updated"
      redirect_to @user
      # Handle a successful update.
    else
      load_new_user_info
      render 'edit'
    end
  end

  def destroy
    user = User.find(params[:id])
    if (current_user == user) && (current_user.admin?)
    	flash[:error] = "Can not delete own admin acount!"
    else
    	user.destroy
      flash[:success] = "User deleted."
    end
    redirect_to users_url
  end

=begin
  def verify_email
    @user = User.find(params[:id])
    verify_token = params[:verify_token]
    if verify_token
      if @user.email_validation_token == User.hash(verify_token)
        @user.validate_email
        render 'verify_email_success'
      else
        flash[:error] = "Not a valid email validation token for this user"
        render 'show_verify_email'
      end
    else
      render 'show_verify_email'
    end
  end
=end

  def username_taken?(uname)
    User.username_taken?
  end

  private

    def user_params
      params.require(:user).permit(:name, :username, :email, :password,
                                   :password_confirmation, :gender, :birthdate,
                                   :geo_country_id, :zip_code,
                                   :age_display_type, :time_zone)
    end

    def load_new_user_info
      if CONFIG[:enable_country?]
        @countries = GeoCountry.get_country_list({default_country: CONFIG[:default_country],
                                              force_reaload: true})
      end
    end

    # Before filters

#    def signed_in_user
#    	unless signed_in?
#    		store_location
#        redirect_to signin_url, notice: "Please sign in."
#      end
#    end

    def correct_user
      user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(user)
    end
    
    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end

    def is_signed_in
    	redirect_to(root_url) if signed_in?
    end

    def new_user(user_params = {})
      user = User.new(user_params)
      omni = session[:omniauth]
      logger.debug("IN new_user!!!. session = #{omni}")
      if omni
        logger.debug("About to call user.apply_omniauth")
        user.apply_omniauth(omni)
        user.auth_type = User::AUTH_OMNIAUTH
      else
        user.auth_type = User::AUTH_LOCAL
      end
      user
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_fields.html.erb
<%= render 'shared/error_messages', target: @user %>

  <% user_obj = f.object %>

  <% if use_name?(user_obj) %>
    <%= f.text_field :name %>
  <% end %>

  <% if use_username?(user_obj) %>
	    <%= f.text_field :username %>
  <% end %>

	<%= f.text_field :email %>
	<%= f.password_field :password %>
  <%= f.password_field :password_confirmation %>

  <% if use_gender?(user_obj) %>
	    <%= f.collection_select( :gender, User::VALID_GENDERS, :to_s, :to_s, {}, { :class => "auto-width" }) %>
  <% end %>

 <% if use_birthdate?(user_obj) %>
	     <%= f.date_select :birthdate,
                    {  :start_year => 1910,
                      :end_year => User::CURRENT_YEAR,
                    },
                    {
                    :class => "small"
                    }
       %>

  <% end %>

 <% if use_time_zone?(user_obj) %>
	  <div class="form-group">
	    <%= f.label :time_zone %>
      <%= f.time_zone_select(:time_zone, ActiveSupport::TimeZone.us_zones, {}, { class: "form-control auto-width", id: "time-zone-select" } )%>
    </div>
  <% end %>

<% if false %>
  <% if require_name? %>
  	<div class="form-group">
	    <%= f.label :name %>
	    <%= f.text_field :name, class: 'form-control' %>
	  </div>
	<% end %>

  <% if require_username? %>
   	<div class="form-group">
	    <%= f.label :username %>
	    <%= f.text_field :username, class: 'form-control' %>
	  </div> 
  <% end %>

	<div class="form-group">
	  <%= f.label :email %>
	  <%= f.text_field :email, class: 'form-control'  %>
	</div>

	<div class="form-group">
	  <%= f.label :password %>
	  <%= f.password_field :password, class: 'form-control'  %>
	</div>

	<div class="form-group">
	  <%= f.label :password_confirmation, "Confirm Password" %>
	  <%= f.password_field :password_confirmation, class: 'form-control'  %>
	</div>

  <% if require_gender? %>
   	<div class="form-group">
	    <%= f.label :gender %>
	    <%= f.collection_select( :gender, User::VALID_GENDERS, :to_s, :to_s, {}, { :class => "small" }) %>
	  </div> 
  <% end %>

<% if require_birthdate? %>
   	<div class="form-group">
	    <%= f.label :birthdate %>
	     <%= f.date_select :birthdate,
                    {  :start_year => 1910,
                      :end_year => User::CURRENT_YEAR,
                    },
                    {
                    :class => "small"
                    }
       %>
	  </div> 

  <% end %>
<% end %>

app/views/users/_user.html.erb
<li>
  <% gravatar_for user, size: 52 %>
  <%= render 'shared/avatar', size: :small, user: user %>
  <%= link_to user.name, show_profile_path(user) %>
  <% if current_user.admin? && !current_user?(user) %>
    | <%= link_to "delete", user, method: :delete,
                                  data: { confirm: "You sure?" } %>
  <% end %>
</li>

app/views/users/edit.html.erb
<% provide(:title, 'Edit user') %>
<h1>Update your profile</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">

    <div class="row">
    	Avatar:
    	<% if @user.avatar_type.blank? || @user.avatar_type == User::NO_AVATAR %>
    	 NONE
    	<% else %>
      	<%= render 'shared/avatar', size: :medium, user: @user %>
      <% end %>
      <%= link_to "Change Avatar", edit_user_avatar_path %>

     <% #  <a href="http://gravatar.com/emails" target="_blank">change</a> %>
    </div>

	  <% if @user.use_username? %>
	    <div class="row">
  		  Username:  <%= @user.username %> - <%= link_to "Change Username", edit_username_path %>
  		</div>
	  <% end %>

    <div class="row">
	    Email: <%= @user.email%> -  <%= link_to "Change Email", edit_user_email_path %>
	  </div>

    <% if @user.use_geo_area? %>
      <div class="row">
        Location:  <%= @user.display_location %> - <%= link_to "Change Location", edit_user_location_path %>
      </div>
    <% end %>

    <div class="row">
    	<% if @user.has_local_authentication? %>
  	    Password: XXXXX - <%= link_to "Reset Password", new_password_reset_path %>
  	  <% else %>
        Local password not set. <%= link_to "Set Password", 
        new_password_reset_path(type: "new") %>
  	  <% end %>
	  </div>

	  <% if User::HAS_USER_EDIT_FIELDS %>
	     <hr/>
      <%= bootstrap_form_for(@user) do |f| %>
        <%= render 'shared/error_messages', target: @user %>

		    <% if @user.use_name? %>
			      <%= f.text_field :name %>
		    <% end %>

  		  <% if @user.use_gender? %>
			    <%= f.collection_select( :gender, User::VALID_GENDERS, :to_s, :to_s, {}, { :class => "auto-width" }) %>
  		  <% end %>

		    <% if @user.use_birthdate? %>
			    <%= f.date_select :birthdate,
		                    {  :start_year => 1910,
		                      :end_year => User::CURRENT_YEAR,
		                    },
		                    {
		                    :class => "small"
		                    }
		      %>
		      <%= f.collection_select( :age_display_type, User::AGE_DISPLAY_TYPES, :to_s, :to_s, {}, { :class => "auto-width" }) %>
  		  <% end %>

 			  <% if @user.use_time_zone? %>
				  <div class="form-group">
			      <%= f.time_zone_select(:time_zone, ActiveSupport::TimeZone.us_zones, {}, { class: "form-control auto-width", id: "time-zone-select" } )%>
			    </div>
			  <% end %>

        <%= f.submit "Save changes", class: "btn btn-lg btn-primary" %>
      <% end %>
    <% end %>

  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>

<%= will_paginate %>

<ul class="users">
  <%= render @users %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= bootstrap_form_for(@user) do |f| %>
      <%= render 'shared/error_messages', target: @user %>

		  <% if @user.use_name? %>
		    <%= f.text_field :name %>
		  <% end %>

		  <% if @user.use_username? %>
			    <%= f.text_field :username %>
		  <% end %>

			<%= f.text_field :email %>

			<% if @user.password_required? %>
  			<%= f.password_field :password %>
	  	  <%= f.password_field :password_confirmation %>
	  	<% end %>

		  <% if @user.use_gender? %>
			    <%= f.collection_select( :gender, User::VALID_GENDERS, :to_s, :to_s, {}, { :class => "auto-width" }) %>
		  <% end %>

		 <% if @user.use_birthdate? %>
			     <%= f.date_select :birthdate,
		                    {  :start_year => 1910,
		                      :end_year => User::CURRENT_YEAR,
		                    },
		                    {
		                    :class => "small"
		                    }
		       %>

			    <%= f.collection_select( :age_display_type, User::AGE_DISPLAY_TYPES, :to_s, :to_s, {}, { :class => "auto-width" }) %>
		  <% end %>

      <% if @user.use_country? %>
        <%= f.collection_select :geo_country_id, @countries, :id, :country_name, {:label => "Country", :prompt => "-- Select a country --"}, { :class => 'auto-width' }  -%>
      <% end %>

		 <% if @user.use_zip_code? %>

       <%= f.text_field :zip_code, {:class=>"auto-width", :size=>"10"} %>
     <% end %>

		 <% if @user.use_time_zone? %>
			  <div class="form-group">
		      <%= f.time_zone_select(:time_zone, ActiveSupport::TimeZone.us_zones, {}, { class: "form-control auto-width", id: "time-zone-select" } )%>
		    </div>
		  <% end %>

      <%= f.submit "Create my account", class: "btn btn-lg btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<h1>THIS IS A USER!!</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'shared/avatar', user: @user, html_class: 'user-profile-avatar' %>
    <h1>
      <%= @user.name %>
    </h1>
  </div>
</div>