config/routes.rb
RailsTemplate::Application.routes.draw do

  match '/auth/:provider/callback', to: 'authentications#create', via: 'get'

  resources :authentications
  resources :password_resets
  resources :profiles 

  resources :users, except: [:show] do
    resources :verify_emails, only: [:new, :create]
    resources :reset_verify_emails, only: [:new, :create]
#    resources :change_usernames, only: [:edit, :update], shallow: true
#    resources :change_emails, only: [:edit, :update], shallow: true
#    resources :change_avatars, only: [:edit, :update], shallow: true
  end

  get '/users/:id', to: "profiles#show"

#  resources :change_usernames, only: [:edit, :update]

  get 'user_location/edit', to: "user_locations#edit", as: :edit_user_location
  post 'user_location', to: "user_locations#update", as: :user_location
 
  get 'user_avatar/edit', to: "change_avatars#edit", as: :edit_user_avatar
  match 'user_avatar', to: "change_avatars#update", as: :user_avatar, via: ['put', 'patch']

  get 'username/edit', to: "change_usernames#edit", as: :edit_username
  match 'username', to: "change_usernames#update", as: :username, via: ['put', 'patch']

  get 'user_email/edit', to: "change_emails#edit", as: :edit_user_email
  match 'user_email', to: "change_emails#update", as: :user_email, via: ['put', 'patch']

  post '/profiles/:id/enable_personal_on', to: "profiles#enable_personal_on",
  as: :enable_personal_profile_on
  resource :personal_profile, except: [:new, :create] do
    member do
      get 'edit_wants'
    end
  end

  get '/users/:user_id/verify_email_token/:verify_token', 
       to: "verify_emails#create", as: 'verify_email_token'
 
  resources :sessions, only: [:new, :create, :destroy]

  root  'static_pages#home'
  match '/signup',  to: 'users#new', via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'

  match '/home', to: 'static_pages#home', via: 'get'
  match '/help', to: 'static_pages#help', via: 'get'
  match '/about', to: 'static_pages#about', via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/error', to: 'static_pages#error', via: 'get'

  match '~:id' => 'profiles#show', :as => :show_profile, via: 'get', :constraints => { :username => /[A-Za-z0-9_\.]+/ }

end

app/views/layouts/_footer.html.erb
<footer class="footer">
 
  
</footer>

app/views/layouts/_header.html.erb
    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">

      <div class="navbar-header">
      	<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#cc-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" id="logo" href="#"><%= app_display_name %></a>
      </div>
      <div class="navbar-collapse collapse" id="cc-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li><%= link_to "Home",  home_path %></li>
          <li><%= link_to "Help",  help_path %></li>
          <li><%= link_to "About", about_path %></li>
          <li><%= link_to "Contact", contact_path %></li>          
          <li><%= link_to "Users", users_path %></li>
        </ul>
        <ul class="nav navbar-nav pull-right">
          <% if signed_in? %>
            <li class="dropdown signin_drop_min_width">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= current_user.username %> <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", show_profile_path(current_user) %></li>
                <li><%= link_to "Edit User", edit_user_path(current_user) %></li>
                <li><%= link_to "Edit Profile", edit_profile_path(current_user) %></li>
                <li><%= link_to "3rd party aps", authentications_path %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Sign out", signout_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Sign in", signin_path %></li>
            <li><%= link_to "Register", new_user_path %></li>
            <% end %>
        </ul>
      </div><!-- /.nav-collapse -->
     
    </div> <!-- navbar -->

app/views/layouts/_shim.html.erb
   <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
    

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |type, value| %>
        <%= content_tag(:div, value, class: "alert #{bootstrap_class_for(type)} fade in") %>
      <% end %> 
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>